// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znvlwsieksjvyetulqhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpudmx3c2lla3NqdnlldHVscWhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMzg0MTcsImV4cCI6MjA3MjYxNDQxN30.v7QH2D3ydsG07Kw_cagN5ZoH_AAznYExbwLbKabGPYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});